---
title: "3depth_comparison"
author: "Laura Seidel"
date: "11/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library (vegan))
suppressPackageStartupMessages(library (dplyr))
suppressPackageStartupMessages(library(SRS))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(ggord))
suppressPackageStartupMessages(library(lattice))
suppressPackageStartupMessages(library(nlme))
suppressPackageStartupMessages(library(lmerTest))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(apeglm))
suppressPackageStartupMessages(library(zinbwave)) 
suppressPackageStartupMessages(library(scran))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(VennDiagram))
suppressPackageStartupMessages(library(pscl))
suppressPackageStartupMessages(library(MASS))
suppressPackageStartupMessages(library(phyloseq))
suppressPackageStartupMessages(library(emmeans))
suppressPackageStartupMessages(library(ggvenn))
```

```{r phytoref - filter}

#Filter wrongly annotated Cyanobacteria with Phytoref

jun_phyto <- read.csv("phytoref/jun_ASVs_seqs_cyano_blast_phytoref.csv", stringsAsFactors = F) %>% 
  group_by(ASV_ID)%>%
  filter(row_number() ==1)%>%
  ungroup()#%>%
 # dplyr::select(ASV_ID, Identifier)

var_phyto <- read.csv("phytoref/var_ASVs_seqs_cyano_blast_phytoref.csv", stringsAsFactors = F)%>%
  group_by(ASV_ID)%>%
  filter(row_number() == 1)%>%
  ungroup()#%>%
 # dplyr::select(ASV_ID, Identifier)

```

```{r read in table}

##meta table
meta<- read.csv("Meta_3depth.csv", stringsAsFactors = FALSE)
meta$depth_bay <- paste(meta$bay, meta$depth_group, sep="_")

#read in data from plate 1
meta_1 <- meta %>%
  filter(plate %in% "varvara")

#counts
#choose specific samples to use
counts <- read.table("ASV_table.tsv",stringsAsFactors =FALSE, header=TRUE) 
  counts <-  dplyr::select(counts,c(1:11,13:47,50:53,59:60,64:65,68:69,72:73))%>%
   gather(sample,count, 2:ncol(.))%>%filter(count > 0)

#taxa

taxa <- read.delim("ASV_tax_species.tsv",stringsAsFactors =FALSE, header=TRUE)%>%
        na_if("")%>%
        replace_na(list(Domain="Unclassified"))%>%
        replace_na(list(Kingdom="Unclassified"))%>%
        replace_na(list(Phylum="Unclassified"))%>%
        replace_na(list(Class="Unclassified"))%>%
        replace_na(list(Order="Unclassified"))%>%
        replace_na(list(Family="Unclassified"))%>%
        replace_na(list(Genus="Unclassified"))%>%
        replace_na(list(Species="Unclassified"))

#Filter samples with reads under 1000
var_tab_2 <- counts %>% 
  left_join(taxa, by="ASV_ID")%>% 
  left_join(meta_1, by="sample")%>%
  group_by(sample_2)%>%
  filter(sum(count) >= 1000) %>%
  ungroup()

#Filter wrongly annotated Cyanos
Cyanos_var_tab <- var_tab_2 %>%
filter(Phylum %in% "Cyanobacteria")%>%
  filter(Class %in% "Unclassified")%>%
  left_join(var_phyto, by="ASV_ID")

var_tab <- var_tab_2%>% 
  dplyr::select(-sample)%>%
     anti_join(Cyanos_var_tab, by="ASV_ID")


#read in data from plate 2

meta_2 <- meta%>%
  filter(plate %in% "june")

#counts

counts_2 <- read.table("ASV_table.tsv",stringsAsFactors =FALSE, header=TRUE)
   counts_2 <-  dplyr::select(counts_2,c(1,53:55,59:61,65:67,80:88))%>%
  gather(sample,count, 2:ncol(.))%>%filter(count > 0)

#taxa

taxa_2 <- read.delim("June/ASV_tax_species.tsv",stringsAsFactors =FALSE, header=TRUE)%>%
        na_if("")%>%
        replace_na(list(Domain="Unclassified"))%>%
        replace_na(list(Kingdom="Unclassified"))%>%
        replace_na(list(Phylum="Unclassified"))%>%
        replace_na(list(Class="Unclassified"))%>%
        replace_na(list(Order="Unclassified"))%>%
        replace_na(list(Family="Unclassified"))%>%
        replace_na(list(Genus="Unclassified"))%>%
        replace_na(list(Species="Unclassified"))

jun_tab_2 <- counts_2 %>% 
  left_join(taxa_2, by="ASV_ID")%>% 
  left_join(meta_2, by="sample")%>%
  group_by(sample_2)%>%
  filter(sum(count) >= 1000) %>%
  ungroup()


Cyanos_jun_tab <- jun_tab_2 %>%
filter(Phylum %in% "Cyanobacteria")%>%
  filter(Class %in% "Unclassified")%>%
  left_join(jun_phyto, by="ASV_ID")

jun_tab <- jun_tab_2%>% 
  dplyr::select(-sample)%>%
     anti_join(Cyanos_jun_tab, by="ASV_ID")


##combine tables

table_sum1 <- rbind(var_tab, jun_tab)
```

```{r calculate relab}
tab_all <- table_sum1 %>%
  group_by(sample_2) %>% 
  mutate(relab = count/sum(count)) %>%
  ungroup()


tab_all$depth_bay <- paste(tab_all$bay, tab_all$depth_group, sep="_")
tab_all$bay_temp <- paste(tab_all$bay, tab_all$temp, sep="_")
tab_all$depth_temp <- paste(tab_all$depth_group, tab_all$temp, sep="_")
```

```{r rarefaction curve - Fig. S3}
countsRAW <- tab_all%>% 
  filter(project %in% "field")%>%
  group_by(sample_2) %>% 
  dplyr::select(ASV_ID, sample_2, count) %>% #select ISV, sample and relab
  spread(ASV_ID,count, fill= 0) %>% #wide format with sequence and relab, filling gaps with 0
  remove_rownames() %>% #remove of row names
  column_to_rownames(var = "sample_2")

#Choose colors for different depth, or just one for all samples, up to you :)
col <- c ("darkgreen","orange2","blue")
grp <- factor(meta$depth_group, levels= c("surface","middle","deep"))
cols <- col[grp]

(raremax <- min(rowSums(countsRAW))) #2650 min. reads in sample

out <-  rarecurve(countsRAW, step = 20, sample = raremax, col = cols , cex = 0.6)
```

```{r nmds - Fig. 2}
#Subset

asvs_subsed <-  tab_all%>% 
  filter(project %in% "field")%>%
  dplyr::select(ASV_ID,sample_2,relab) %>% 
  spread(ASV_ID,relab, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample_2")

#NMDS
 # calculate bray curtis distances with metaMDS function, double check autotransform and trace in metaMDS help!!!
nmds.asvs.h.bc <- metaMDS(asvs_subsed ,
                             distance = "bray",
                             k = 3,
                             trymax = 50,
                             autotransform = FALSE,
                             trace = FALSE)


nmds.seed.asvs.bc.df <- as.data.frame(nmds.asvs.h.bc$points) %>%
      rownames_to_column(var ="sample_2") %>%
       dplyr::rename(NMDS1 = MDS1, NMDS2 = MDS2)
 
     # check the stress plot should be a nearly linear fit
nmds.asvs.h.bc.stress <- stressplot(nmds.asvs.h.bc)


tab_all$depth_bay <- factor(tab_all$depth_bay,levels=c("CONTROL_surface","CONTROL_middle","CONTROL_deep","TEMP_AFFECT_surface","TEMP_AFFECT_middle","TEMP_AFFECT_deep"))

tab_all$depth_group <- factor(tab_all$depth_group,levels=c("surface","middle","deep"))

p <- nmds.seed.asvs.bc.df %>% inner_join (tab_all, by="sample_2")%>%
  ungroup()%>%
  ggplot( aes(x=NMDS1, y=NMDS2, color=bay, shape=depth_group)) +
  #scale_color_manual(values=c( "lightblue","deepskyblue2","blue4","bisque","darkorange", "darkred"))+
  scale_color_manual(values=c("blue","orange"))+
  geom_point(size = 8) +
  theme_classic() +
  theme(legend.position = "bottom")+

annotate("text",label="stress value = 0.063",x=-1, y=-1)

p
```

```{r alpha diversity - Fig. 1}
#based on SRS

example_input_data_SED <- tab_all %>%
  dplyr::select(ASV_ID, sample_2, count)%>%  #select ISV, sample and relab
  spread(sample_2,count, fill= 0) %>% #wide format with sequence and relab, filling gaps with 0
  remove_rownames() %>% #remove of row names
  column_to_rownames(var ="ASV_ID")

#(e.g. species counts of the library with the lowest sequencing depth):
Cmin_SED <- min(colSums(example_input_data_SED))
Cmin_SED

SRS_output_SED <- SRS(data = example_input_data_SED, Cmin = Cmin_SED)
SRS_output_SED


##Shannon´s H Diversity
SRSshannon_SED<- SRS_output_SED %>%
  t()%>%
  data.frame()%>% 
  rownames_to_column(var="sample_2")%>% 
  plyr::ddply(~sample_2, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
  dplyr::rename(shannon= V1) %>% #Shannon 
  left_join(meta, by="sample_2")

SRSshannon_SED$depth_group<- factor(SRSshannon_SED$depth_group,levels=c("surface","middle","deep"))


#Plot
SRSshannon_SED %>%
  filter(project %in% "field")%>%
   group_by(depth_group, temp_2, project, bay)%>%
  mutate(mean=mean(shannon))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
 ggplot(aes(x = depth_group, y = mean, color=as.factor(bay), shape=depth_group)) +
  geom_point(size=6) +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
  scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(x = "depth", y = "Shannon´s H Index") +
    theme_classic()+
  theme(text = element_text(size = 14)) +
  theme(panel.grid = element_blank(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank())+
  facet_wrap(~bay)+
  ylim(3,8)+
   theme(legend.position = "bottom")

```

```{r statistics - alpha diversity}
SRS_2 <- SRSshannon_SED %>%
  filter(project %in% "field")

#field samples

B8 <- lm(shannon ~ 1 + bay/site + depth_group + bay/site*depth_group, method="REML", data=SRS_2)

test <- anova(B8)
p.adjust(test2$`Pr(>F)`, method="bonferroni")
test2 <-as.data.frame(test)

summary(B8)$fstatistic

library(emmeans)

e8 <- emmeans(B8, spec="bay",by="depth_group", contr="pairwise")

p.adjust(summary(e8)$contrasts$p.value, method="bonferroni")
as.data.frame(e8)


e9 <- emmeans(B8, spec="depth_group",by="bay", contr="pairwise", adjust="tukey")
as.data.frame(e9)
p.adjust(summary(e9)$contrasts$p.value, method="bonferroni")
```

```{r Differential abundance analysis using DESeq2}

###Make an phyloseq object
OTU <- tab_all%>%
  filter(project %in% "field")%>%
  group_by(Class, sample_2)%>%
  summarise(count=sum(count))%>%
  dplyr::select(Class, sample_2, count)%>% 
  spread(sample_2, count,fill=0 ) %>%
  column_to_rownames("Class")

TAXA <- taxa %>%
  dplyr::select("Kingdom","Order","Class")%>%
  group_by(Class)%>%
  filter(row_number() ==1)%>%
  ungroup()%>%
 # semi_join(tab_all, by=c("Kingdom","Order","Class"))%>% 
  remove_rownames()%>%
  column_to_rownames(var="Class")

SAMPLES <- meta %>%
          filter(project %in% "field")%>%
          remove_rownames() %>% 
          column_to_rownames(var="sample_2")

OTU <- as.matrix(OTU)
TAXA <- as.matrix(TAXA)

  OTU = otu_table(OTU, taxa_are_rows = TRUE)
  TAX = tax_table(TAXA)
  samples = sample_data(SAMPLES)
  
  carbom <- phyloseq(OTU, TAX, samples)
  carbom

##Get rid of low abundant Taxa
species_counts_df <- data.frame(otu_table(carbom))
(sum(colSums(species_counts_df == 0))) / (nrow(species_counts_df) * ncol(species_counts_df))#43 % zeros in our matrix

###~ 95 % zeros in our matrix, now we are droping taxa not seen in at least 20 % of the samples
(carbom <- filter_taxa(carbom, function(x) sum(x > 0) > (0.2*length(x)), TRUE))

###Assessing zero proportion after filtering
species_counts_df <- data.frame(otu_table(carbom))
species_counts_df <- data.frame(t(species_counts_df))


dds_zinbwave <- phyloseq_to_deseq2(carbom, ~ bay*depth_group)
ds_zinbwave <- zinbwave(dds_zinbwave,
                   X="~ 1",
                   epsilon = 1e10,
                   verbose = TRUE,
                   K = 0,
                   observationalWeights = TRUE,
                   BPPARAM = BiocParallel::SerialParam())


dds_zinb <- DESeqDataSet(dds_zinbwave, design = ~ bay*depth_group)
   dds_zinb$group <- factor(paste0(dds_zinb$bay, dds_zinb$depth_group))
   design(dds_zinb)<- ~group
dds_zinb <- estimateSizeFactors(dds_zinb, type="poscounts")
scr <- computeSumFactors(dds_zinb) 

sizeFactors(dds_zinb) <- sizeFactors(scr)

###Fit the model use the LRT 
dds_zinb <- DESeq(dds_zinb, test="LRT", reduced=~1, sfType="poscounts",
                  minmu=1e-6, minReplicatesForReplace=Inf, fitType = "local")

plotMA(dds_zinb)
plotDispEsts(dds_zinb)  

###Make contrast so you can differentiate between the groups you are looking for
   resultsNames(dds_zinb)
   DE2_TEMP_SURF_MID <- results(dds_zinb, contrast=c("group","TEMP_AFFECTsurface","TEMP_AFFECTmiddle")) 
   DE2_TEMP_SURF_DEEP <-results(dds_zinb, contrast=c("group","TEMP_AFFECTsurface","TEMP_AFFECTdeep")) 
   DE2_TEMP_MID_DEEP <-results(dds_zinb, contrast=c("group","TEMP_AFFECTmiddle","TEMP_AFFECTdeep"))
  
   DE2_CON_SURF_MID <-results(dds_zinb, contrast=c("group","CONTROLsurface","CONTROLmiddle"))
   DE2_CON_SURF_DEEP <-results(dds_zinb, contrast=c("group","CONTROLsurface","CONTROLdeep"))
   DE2_CON_MID_DEEP <-results(dds_zinb, contrast=c("group","CONTROLmiddle","CONTROLdeep"))
   
   DE2_CON_TEMP_SURF_SURF <-results(dds_zinb, contrast=c("group","CONTROLsurface","TEMP_AFFECTsurface"))
   DE2_CON_TEMP_MID_MID <-results(dds_zinb, contrast=c("group","CONTROLmiddle","TEMP_AFFECTmiddle"))
   DE2_CON_TEMP_DEEP_DEEP <-results(dds_zinb, contrast=c("group","CONTROLdeep","TEMP_AFFECTdeep"))
##make it readable 
   
   TAXA_1 <- as.data.frame(TAXA) %>% rownames_to_column("Class")
   
   
   
    DE2_results <- data.frame(DE2_CON_TEMP_DEEP_DEEP)
    baseMeanPerLvl <- sapply( levels(dds_zinb$group), function(lvl) rowMeans(counts(dds_zinb,normalized=TRUE)[,dds_zinb$group == lvl] ) )
    DE2_results <-merge(DE2_results,baseMeanPerLvl, by="row.names")
    DE2_results<- DE2_results[,c(1,2,8,11,3,4,5,6,7)]

    sorted_DE2_results <- DE2_results[order(-DE2_results$baseMean),]
    colnames(sorted_DE2_results)[1] <- "Class"
   
    sorted_taxa <- sorted_DE2_results %>% left_join(TAXA_1, by="Class")

```

```{r DA tables combined}
#Temp Surf MID

DE2_TEMP_SURF_MID_tab<- read.csv("DIFF_ABUND_TEMP_SURF_MID_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-TEMP_AFFECTsurface,-TEMP_AFFECTmiddle)%>%
  mutate(depth_group = case_when(log2FoldChange < 0 ~ "middle", 
                               log2FoldChange > 0 ~ "surface"))

asv_TEMP_SURF_MID <- tab_all %>% 
  filter(depth_bay %in% c("TEMP_AFFECT_surface","TEMP_AFFECT_middle"))%>%
  filter(project %in% "field")%>%
  dplyr::select(Kingdom, Phylum, Class, Order, depth_group)

TEMP_SURF_MID_FULL <- DE2_TEMP_SURF_MID_tab%>% 
            left_join(asv_TEMP_SURF_MID, by=c("Kingdom","Order","Class","depth_group"))%>%
  na.omit()


#Temp Surf deep

DE2_TEMP_SURF_DEEP_tab<- read.csv("DIFF_ABUND_TEMP_SURF_DEEP_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-TEMP_AFFECTsurface,-TEMP_AFFECTdeep)%>%
  mutate(depth_group = case_when(log2FoldChange < 0 ~ "DEEP", 
                               log2FoldChange > 0 ~ "SURFACE"))

asv_TEMP_SURF_DEEP <- tab_all %>% 
  filter(depth_bay %in% c("TEMP_AFFECT_surface","TEMP_AFFECT_deep"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

TEMP_SURF_DEEP_FULL <- DE2_TEMP_SURF_DEEP_tab %>% 
            left_join(asv_TEMP_SURF_DEEP, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()


#Temp mid deep

DE2_TEMP_MID_DEEP_tab<- read.csv("DIFF_ABUND_TEMP_MID_DEEP_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-TEMP_AFFECTmiddle,-TEMP_AFFECTdeep)%>%
  mutate(depth_group = case_when(log2FoldChange < 0 ~ "DEEP", 
                               log2FoldChange > 0 ~ "MIDDLE"))

asv_TEMP_MID_DEEP <- tab_all %>% 
  filter(depth_bay %in% c("TEMP_AFFECT_middle","TEMP_AFFECT_deep"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

TEMP_MID_DEEP_FULL <- DE2_TEMP_MID_DEEP_tab %>% 
            left_join(asv_TEMP_MID_DEEP, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()


#Con surf mid

DE2_CON_SURF_MID_tab<- read.csv("DIFF_ABUND_CON_SURF_MID_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-CONTROLsurface,-CONTROLmiddle)%>%
  mutate(depth_group = case_when(log2FoldChange < 0 ~ "MIDDLE", 
                               log2FoldChange > 0 ~ "SURFACE"))

asv_CON_SURF_MID <- tab_all %>% 
  filter(depth_bay %in% c("CONTROL_surface","CONTROL_middle"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

CON_SURF_MID_FULL <- DE2_CON_SURF_MID_tab %>% 
            left_join(asv_CON_SURF_MID, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()


#Con surf deep

DE2_CON_SURF_DEEP_tab<- read.csv("DIFF_ABUND_CON_SURF_DEEP_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-CONTROLsurface,-CONTROLdeep)%>%
  mutate(depth_group = case_when(log2FoldChange < 0 ~ "DEEP", 
                               log2FoldChange > 0 ~ "SURFACE"))

asv_CON_SURF_DEEP <- tab_all %>% 
  filter(depth_bay %in% c("CONTROL_surface","CONTROL_deep"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

CON_SURF_DEEP_FULL <- DE2_CON_SURF_DEEP_tab %>% 
            left_join(asv_CON_SURF_DEEP, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()


#Con mid deep

DE2_CON_MID_DEEP_tab<- read.csv("DIFF_ABUND_CON_MID_DEEP_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-CONTROLmiddle,-CONTROLdeep)%>%
  mutate(depth_group = case_when(log2FoldChange < 0 ~ "DEEP", 
                               log2FoldChange > 0 ~ "MIDDLE"))

asv_CON_MID_DEEP <- tab_all %>% 
  filter(depth_bay %in% c("CONTROL_middle","CONTROL_deep"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

CON_MID_DEEP_FULL <- DE2_CON_MID_DEEP_tab %>% 
            left_join(asv_CON_MID_DEEP, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()


#TEMP CON surface

DE2_TEMP_CON_SURF_tab<- read.csv("DIFF_ABUND_TEMP_CON_SURF_SURF_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-TEMP_AFFECTsurface,-CONTROLsurface)%>%
  mutate(bay = case_when(log2FoldChange < 0 ~ "TEMP_AFFECT", 
                               log2FoldChange > 0 ~ "CONTROL"))

asv_TEMP_CON_SURF <- tab_all %>% 
  filter(depth_bay %in% c("TEMP_AFFECT_surface","CONTROL_surface"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

TEMP_CON_SURF_FULL <- DE2_TEMP_CON_SURF_tab %>% 
            left_join(asv_TEMP_CON_SURF, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()


#TEMP CON middle

DE2_TEMP_CON_MID_tab<- read.csv("DIFF_ABUND_TEMP_CON_MID_MID_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
    dplyr::select(-TEMP_AFFECTmiddle,-CONTROLmiddle)%>%
  mutate(bay = case_when(log2FoldChange < 0 ~ "TEMP_AFFECT", 
                               log2FoldChange > 0 ~ "CONTROL"))



asv_TEMP_CON_MID <- tab_all %>% 
  filter(depth_bay %in% c("TEMP_AFFECT_middle","CONTROL_middle"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

TEMP_CON_MID_FULL <- DE2_TEMP_CON_MID_tab %>% 
            left_join(asv_TEMP_CON_MID, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()



#TEMP CON deep

DE2_TEMP_CON_DEEP_tab<- read.csv("DIFF_ABUND_TEMP_CON_DEEP_DEEP_CLASS.csv", stringsAsFactors = FALSE)%>% 
  filter(padj <0.05)%>%
  filter(!between(log2FoldChange, -1, 1))%>%
  dplyr::select(-TEMP_AFFECTdeep,-CONTROLdeep)%>%
  mutate(bay = case_when(log2FoldChange < 0 ~ "TEMP_AFFECT", 
                               log2FoldChange > 0 ~ "CONTROL"))

asv_TEMP_CON_DEEP <- tab_all %>% 
  filter(depth_bay %in% c("TEMP_AFFECT_deep","CONTROL_deep"))%>%
  filter(project %in% "field")%>%
  dplyr::select(count, Kingdom, Phylum, Class, Order, sample_2, bay, project, site, temp, temp_2, relab, depth_bay, bay_temp, depth_temp)

TEMP_CON_DEEP_FULL <- DE2_TEMP_CON_DEEP_tab %>% 
            left_join(asv_TEMP_CON_DEEP, by=c("Kingdom","Order","Class","bay"))%>%
  na.omit()

TEMP_CON_DEEP_FULL<- TEMP_CON_DEEP_FULL%>%  
mutate(comp = "TEMP_CON_DEEP_FULL")

TEMP_CON_MID_FULL <- TEMP_CON_MID_FULL %>%
  mutate(comp = "TEMP_CON_MID_FULL")

TEMP_CON_SURF_FULL <- TEMP_CON_SURF_FULL%>%
  mutate(comp= "TEMP_CON_SURF_FULL")


BAY_COMP_ALL <- rbind(TEMP_CON_DEEP_FULL,TEMP_CON_MID_FULL,TEMP_CON_SURF_FULL)

##COMBINE
##TEMP
DE2_TEMP_SURF_MID_FULL_tab <- DE2_TEMP_SURF_MID_tab %>%
  mutate(comp = "TEMP_SURF_MID_FULL")

DE2_TEMP_SURF_DEEP_tab <- DE2_TEMP_SURF_DEEP_tab%>%
  mutate(comp = "TEMP_SURF_DEEP_FULL")

DE2_TEMP_MID_DEEP_tab<- DE2_TEMP_MID_DEEP_tab %>%
  mutate(comp = "TEMP_MID_DEEP_FULL")

temp_all <- rbind(DE2_TEMP_SURF_MID_FULL_tab,
DE2_TEMP_SURF_DEEP_tab,DE2_TEMP_MID_DEEP_tab)

##CON
DE2_CON_SURF_MID_tab <- DE2_CON_SURF_MID_tab %>% 
  mutate(comp = "CON_SURF_MID_FULL")

DE2_CON_SURF_DEEP_tab <- DE2_CON_SURF_DEEP_tab %>%
  mutate(comp ="CON_SURF_DEEP_FULL")

DE2_CON_MID_DEEP_tab <- DE2_CON_MID_DEEP_tab%>%
  mutate(comp = "CON_MID_DEEP_FULL")

con_all <- rbind(DE2_CON_SURF_MID_tab, DE2_CON_SURF_DEEP_tab, DE2_CON_MID_DEEP_tab)

all_all <- rbind(temp_all, con_all)

write.csv(all_all, "DE2_compare_within_bays_sig_all.csv")
```

```{r DA - Fig. 4}

BAY_COMP_ALL %>%
 group_by(Phylum,Class, bay, comp,site)%>%
  summarise(log2FoldChange = mean(log2FoldChange))%>%
     summarise(log2FoldChange = mean(log2FoldChange))%>%
  ungroup()%>%
      filter(!between(log2FoldChange, -1, 1))%>%
ggplot(aes(x=reorder(Class,-log2FoldChange),y=log2FoldChange, fill=comp))+
geom_col() + coord_flip()+
scale_fill_manual(values=c("#9e6ebd",
"#7aa457",
"#cb6751"),
labels=c("Surface","Middle","Deep"))+
  ggtitle(" Heated vs. Control")+
  xlab("Class")+
  ylab("average log2FoldChange >1")+
  labs(fill="bay")+
  theme_bw()+
      theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="bottom")
```

```{r Sulfate data}
meta$depth_group<- factor(meta$depth_group,levels=c("surface","middle","deep"))

 sulf <-meta %>%
  filter(project %in% "field")%>%
  group_by(bay, depth_group)%>%
  mutate(sd= sd(sulfate))%>%
  mutate(mean=mean(sulfate))%>%
  ggplot(aes(x=depth_group, y=mean, group=bay, fill=bay))+
    geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2, color="grey"
                 )+ 
  scale_fill_manual(values=c("blue","orange"))+
  geom_line(color="grey")+
  geom_point(shape=21, size=6)+
  theme_classic()+
  ylim(0,5.5)+
  ggtitle("Sulfate concentration")+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="bottom")+
  ylab("mM")+
  xlab("depth")+
  labs(fill="bay")
 
 
 #Sulfate stats
 meta_sulf <- meta %>%
  filter(project %in% "field")%>%
  group_by(bay, depth_group)%>%
    mutate(sd= sd(sulfate))%>%
  mutate(mean=mean(sulfate))%>%
  ungroup()


write.csv(meta_sulf, "sulfate_values_3_depth.csv")


B8 <- lm(sulfate ~ 1 + bay/site + depth_group + bay/site*depth_group, method="REML", data=meta_sulf)
test <- anova(B8)
test2<- as.data.frame(test)
p.adjust(test2$`Pr(>F)`, method="bonferroni")

summary(B8)$fstatistic



e8 <- emmeans(B8, spec="bay",by="depth_group", contr="pairwise")
as.data.frame(e8)
p.adjust(summary(e8)$contrasts$p.value, method="bonferroni")

e9 <- emmeans(B8, spec="depth_group",by="bay", contr="pairwise")
as.data.frame(e9)
p.adjust(summary(e9)$contrasts$p.value, method="bonferroni")
 
```

```{r Fig. 3}
tab_all$depth_group<- factor(tab_all$depth_group,levels=c("surface","middle","deep"))

tab_all %>%
 # filter(project %in% "field")%>%
  filter(!Domain %in% "Unclassified")%>%
  group_by(Domain,depth_group, bay, project, sample_2)%>%
    summarise(mean=sum(relab))%>%
  summarise(mean=mean(mean))%>%
  ungroup()%>%
ggplot( aes(fill=Domain, y=mean, x=depth_group)) + 
  geom_bar(position="stack", stat="identity")+
  facet_grid(~project+bay)

#Phylum

field_king <- tab_all %>%
  filter(project %in% "field")%>%
  filter(!Domain %in% "Unclassified")%>%
  group_by(Kingdom,depth_group, bay, project, sample_2)%>%
  summarise(mean=sum(relab))%>%
  summarise(mean=mean(mean))%>%
  ungroup()%>%
  ggplot( aes(fill=Kingdom, y=mean, x=depth_group)) + 
   geom_col() +
  scale_x_discrete() +
  geom_bar(width = 1, stat = "identity", col="black")+
  coord_polar("y", start=0)+
  # geom_bar(position="stack", stat="identity", alpha=0.7)+
  scale_fill_manual(values=c("#b75fb3","#b88f3e"))+
  facet_wrap(~bay,nrow=2)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="bottom")+
  ggtitle("Kingdom")+
  labs(fill="bay")

#Archaea

tab_all$depth_group<- factor(tab_all$depth_group,levels=c("deep","middle","surface"))
field_class_ar <- tab_all %>%
  filter(project %in% "field")%>%
  filter(!Domain %in% "Unclassified")%>%
  filter(Domain %in% "Archaea")%>%
 # filter(Phylum %in% "Thermoproteota")%>%
  group_by(Class,depth_group, bay, project, sample_2)%>%
    summarise(mean=sum(relab))%>%
  summarise(mean=mean(mean))%>%
  #filter(mean>0.01)%>%
  ungroup()%>%
ggplot( aes(fill=Class, y=mean, x=depth_group)) + 
  geom_bar(position="stack", stat="identity")+
  scale_fill_manual(values=c("#dd3e77","#b34967","#e5838b","#d3404b","#a9593c","#d15a2a","#da9754","#cba630","#857331","#a1b34a","#4d7c3a","#5bb848","#5bb780","#3dbbb8","#62a0d8","#5670ba","#7169de","#b28ddb","#7f4ba6","#c864d3","#d283b8","#a93f89","#da46a5","#924c6a"))+
  facet_grid(~bay)+
      theme_classic()+
  coord_flip()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="bottom")+
  ggtitle("Archaea")+
  ylab("relative abundance %")+
  xlab("depth")+
  labs(fill="bay")

#Bacteria

field_ba<-tab_all %>%
  filter(project %in% "field")%>%
  filter(!Domain %in% "Unclassified")%>%
  filter(!Domain %in% "Archaea")%>%
  group_by(Class,depth_group, bay, project, sample_2)%>%
    summarise(mean=sum(relab))%>%
  summarise(mean=mean(mean))%>%
  filter(mean>0.01)%>%
  ungroup()%>%
ggplot( aes(fill=Class, y=mean, x=depth_group)) + 
  geom_bar(position="stack", stat="identity")+
  scale_fill_manual(values=c("#ff8587","#ff2d2f","#ff8664","#843d00","#c37c00","#ffde8b","#ffe91c","#90a400","#2c3200","#99cf00","#c5ff6a","#009d61","#00422e","#01f4e4","#96ecff","#00b4f0","#004a66","#005cb2","#4960ff","#250070","#4f005b","#ffb3cf","#b9006b","#ff2890"))+
  facet_grid(~bay)+
    theme_classic()+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="bottom")+
  ggtitle("Bacteria")+
  xlab("depth")+
  ylab("relative abundance >1 %")+
  labs(fill="bay")+
    coord_flip()

sec <- ggarrange(field_class_ar, field_ba, nrow=2)


two <- ggarrange(field_king, sec, ncol=2)
```

```{r Fig. 5}
##overview Class of DIFF abundance results


Class <- BAY_COMP_ALL %>% 
  filter(!between(log2FoldChange, -2, 2))%>%
  group_by(Class)%>%
  summarize(count=sum(count))%>%
  dplyr::select(Class)
###Check on top Class relative abundance base don the class from Diff abundance analysis - is there anything interesting? 

 bac_2 <-tab_all %>%
     inner_join(Class, by="Class")%>%
  filter(project %in% "field")%>%
  filter(!Domain %in% "Unclassified")%>%
  #filter(!Domain %in% "Archaea")%>%
 # filter(Class %in% c("UBA4738","SM23-31","Altarchaeia","Blastocatellia","UBA11346","UBA9042","GWE2-31-10","CG2-30-54-11","UBA796","Dehalobacteriia","Brevinematia"))%>%
  group_by(Phylum,Class,depth_group, bay, project, sample_2)%>%
    summarise(mean=sum(relab))%>%
  summarise(mean=mean(mean))%>%
  ungroup()%>%
 filter(mean >0.01)%>%
ggplot( aes(fill=Class, y=mean, x=depth_group, alpha=0.9)) + 
  geom_bar(position="stack", stat="identity", alpha=0.9)+
  scale_fill_manual(values=c("#dd3e77","#b34967","#e5838b","#d3404b","#a9593c","#d15a2a","#da9754","#cba630","#857331","#a1b34a","#4d7c3a","#5bb848","#5bb780","#3dbbb8","#62a0d8",
"#5670ba","#7169de","#b28ddb","#7f4ba6","#c864d3","#d283b8","#a93f89","#da46a5","#924c6a","grey76"))+
  facet_grid(~bay)+
      theme_classic()+
  coord_flip()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="bottom")+
  ggtitle("Highest Diff.abundance")+
  ylab("relative abundance %")+
  xlab("depth")+
  labs(fill="Family")
 
 ###Deep  CHECK FOR ORIGINAL SEQUENCES AS WITH DIFF EX THERE WILL BE NO OVERLAPPING

Class <- BAY_COMP_ALL %>% 
    filter(!between(log2FoldChange, -2, 2))%>%
  group_by(Class)%>%
  summarize(count=sum(count))%>%
  dplyr::select(Class)

#Surface

venn <-tab_all %>%
  inner_join(Class, by="Class")%>%
  filter(project %in% "field")%>%
  filter(depth_group %in% "surface")%>%#
    group_by(Family,depth_group, bay, sample_2)%>%
    mutate(mean=sum(relab))%>%
  #summarise(mean=mean(mean))%>%
  ungroup()%>%
 filter(mean >0.01)%>%
 # filter(Class %in% c("Sumerlaeia","Lokiarchaeia","WOR-3","Dissulfuribacteria","Thermoplasmata","Marinamargulisbacteria"))%>%
   group_by(ASV_ID, Family, sample_2, bay, depth_group )%>%
 summarize(count = sum(count))%>%
 ##   summarise(count = sum(count))%>%
  ungroup()

venn %>% 
  filter(bay == "TEMP_AFFECT") %>% pull(ASV_ID)%>%
  unique() -> temp_affect

venn %>% 
  filter(bay == "CONTROL") %>% pull(ASV_ID)%>%
  unique() -> control

surf<-  venn%>%
  mutate(Heated = if_else(ASV_ID %in% temp_affect, TRUE,FALSE)) %>%
  mutate(Control = if_else(ASV_ID %in%control, TRUE,FALSE)) %>%
  ggplot(aes(A = Heated, B = Control)) +
  geom_venn(
    show_percentage = FALSE,
    fill_color = c("orange","blue"),
    fill_alpha = .5,
    set_name_size = 15/.pt, text_size = 15/.pt,
    stroke_size = .5) + 
  coord_fixed(expand = FALSE) +
  theme_void() + 
  theme(aspect.ratio = 1, plot.tag.position = c(.1,1.02),
        plot.margin = margin(0,0,0,0))+
  ggtitle("Surface")

 #middle
 venn <-tab_all %>%
     inner_join(Class, by="Class")%>%
  filter(project %in% "field")%>%
  filter(depth_group %in% "middle")%>%
 # filter(Class %in% c("Sumerlaeia","Lokiarchaeia","WOR-3","Dissulfuribacteria","Thermoplasmata","Marinamargulisbacteria"))%>%
group_by(Family,depth_group, bay, sample_2)%>%
    mutate(mean=sum(relab))%>%
  #summarise(mean=mean(mean))%>%
  ungroup()%>%
 filter(mean >0.01)%>%
 # filter(Class %in% c("Sumerlaeia","Lokiarchaeia","WOR-3","Dissulfuribacteria","Thermoplasmata","Marinamargulisbacteria"))%>%
   group_by(ASV_ID, Family, sample_2, bay, depth_group )%>%
 summarize(count = sum(count))%>%
 ##   summarise(count = sum(count))%>%
  ungroup()
 
venn %>% 
  filter(bay == "TEMP_AFFECT") %>% pull(ASV_ID)%>%
  unique() -> temp_affect

venn %>% 
  filter(bay == "CONTROL") %>% pull(ASV_ID)%>%
  unique() -> control

 middle <- venn%>%
  mutate(Heated = if_else(ASV_ID %in% temp_affect, TRUE,FALSE)) %>%
  mutate(Control = if_else(ASV_ID %in%control, TRUE,FALSE)) %>%
  ggplot(aes(A = Heated, B = Control)) +
  geom_venn(
    show_percentage = FALSE,
    fill_color = c("orange","blue"),
    fill_alpha = .5,
    set_name_size = 15/.pt, text_size = 15/.pt,
    stroke_size = .5) + 
  coord_fixed(expand = FALSE) +
  theme_void() + 
  theme(aspect.ratio = 1, plot.tag.position = c(.1,1.02),
        plot.margin = margin(0,0,0,0))+
  ggtitle("Middle")
 
 #deep
  venn <-tab_all %>%
      inner_join(Class, by="Class")%>%
  filter(project %in% "field")%>%
  filter(depth_group %in% "deep")%>%
 # filter(Class %in% c("Sumerlaeia","Lokiarchaeia","WOR-3","Dissulfuribacteria","Thermoplasmata","Marinamargulisbacteria"))%>%
 group_by(Family,depth_group, bay, sample_2)%>%
    mutate(mean=sum(relab))%>%
  #summarise(mean=mean(mean))%>%
  ungroup()%>%
 filter(mean >0.01)%>%
 # filter(Class %in% c("Sumerlaeia","Lokiarchaeia","WOR-3","Dissulfuribacteria","Thermoplasmata","Marinamargulisbacteria"))%>%
   group_by(ASV_ID, Family, sample_2, bay, depth_group )%>%
 summarize(count = sum(count))%>%
 ##   summarise(count = sum(count))%>%
  ungroup()

venn %>% 
  filter(bay == "TEMP_AFFECT") %>% pull(ASV_ID)%>%
  unique() -> temp_affect

venn %>% 
  filter(bay == "CONTROL") %>% pull(ASV_ID)%>%
  unique() -> control

 deep <- venn%>%
  mutate(Heated = if_else(ASV_ID %in% temp_affect, TRUE,FALSE)) %>%
  mutate(Control = if_else(ASV_ID %in%control, TRUE,FALSE)) %>%
  ggplot(aes(A = Heated, B = Control)) +
  geom_venn(
    show_percentage = FALSE,
    fill_color = c("orange","blue"),
    fill_alpha = .5,
    set_name_size = 15/.pt, text_size = 15/.pt,
    stroke_size = .5) + 
  coord_fixed(expand = FALSE) +
  theme_void() + 
  theme(aspect.ratio = 1, plot.tag.position = c(.1,1.02),
        plot.margin = margin(0,0,0,0))+
  ggtitle("Deep")

 shared <- ggarrange(surf, middle, deep, ncol=3)
 
 bottom <- ggarrange(shared, sulf, ncol=2)
 ggarrange( bac_2, bottom, nrow=2)
```

```{r session-info}
# Display current R session information
sessionInfo()
```